apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-two
  labels:
    app: my-app-two
spec:
  replicas:
  selector:
    matchLabels:
      app: my-app-two
  template:
    metadata:
      labels:
        app: my-app-two
    spec:
      imagePullSecrets:
        - name: my-registry-key-two
      containers:
        - name: my-app-two
          image: 788577008603.dkr.ecr.eu-north-1.amazonaws.com/my-app:1.1
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
